version: "3.8"
networks:
  tailscale:
    external: true
    name: tailscale-relay_tailscale

services:
  ar-art:
    container_name: ar-art
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    networks:
      - tailscale
